### ISSUE TITLE
Fallback not possible for mclock (monotonic clock)

### ISSUE THREAD

**Issue by tansy** [fwojcik/smhasher3#3]
In Linux I have a trouble building it as it is not detecting monotonic clock correctly.

```
build $ cmake ..
(...)
-- Probing high-resolution timing functions
CMake Error at platform/functions.cmake:109 (message):
  Fallback not possible for mclock (monotonic clock)! Cannot continue.

Call Stack (most recent call first):
  platform/timing.cmake:17 (findVariant)
  CMakeLists.txt:102 (include)
```
And `build/curvariant.h` come from `platform/mclock_variant2.h`, which is for windows.

As I couldn't manage that I have removed that from CMakeList.txt:101 and manually procured Linux version in `build/curvariant.h`.

**Comment by tansy** [comment]
Just read to post it on gitlab.

**Comment by fwojcik** [comment]
I thank you so much for your contributions! I am unfortunately going to 
be unavailable for the remainder of the year due to a family emergency, 
but I will incorporate your changes early next year.

For this one, the "current" contents of curvariant.h are expected to be 
the last variant that was attempted, so seeing the windows variant is 
normal, given that the usual Linux variant code did not work for 
whatever reason.

If could you could please share (on GitLab) the code you used to 
implement the monotonic clock functions on your system, it would be 
extremely helpful.

Thanks again!
